{{- $name := include "aggregator.name" . -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $name }}-internal-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}-internal-ingress

{{- with .Values.ingress.internal.annotations }}
  annotations:
    kubernetes.io/ingress.class: traefik-internal
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
    {{ range $hosts:= .Values.ingress.internal.hosts }}
    - host: {{ $hosts.hostname }}
      http:
        paths:
          - path: {{ $hosts.path }}
            backend:
              serviceName: {{ $name }}-service
              servicePort: {{ $hosts.servicePort }}
    {{- end }}
  tls:
    - hosts:
      {{- range $i, $hosts:= .Values.ingress.internal.hosts }}
        - {{ $hosts.hostname }}
      {{- end }}
      secretName: {{ $name }}-internal-tls
